name: Tox

on:
  pull_request:
    types: [opened, edited]
    branches: [development, master]

  push:
    branches: [development, master]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
